-- AUTO-GENERATED by battle.py. Do not edit.
ArmyConfig = {
	Attacker = { { type = "e3", count = 6 }, { type = "bggy", count = 2 }, { type = "bike", count = 4 }, { type = "apc", count = 3 }, { type = "ftnk", count = 1 }, { type = "stnk", count = 1 } },
	Defender = { { type = "e2", count = 2 }, { type = "e4", count = 1 }, { type = "arty", count = 2 }, { type = "mtnk", count = 6 } },
	GridCols = 4,
	Seed = 6,
}
