#!/usr/bin/env python3
"""Opera Battles: headless OpenRA battle driver.

Renders config.lua from a battle spec, installs the arena map, boots the game
straight into the mission, tails lua.log until E|DONE, optionally records the
Xvfb display to mp4, and writes out/stats.json.

Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import signal
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DISPLAY = ":99"
SCREEN_W, SCREEN_H = 1280, 720
HEADLESS_W, HEADLESS_H = 320, 240
TURBO = "battle-turbo"
GAME_UNIT = "opera-battle-game"
POLL_S = 0.05
DEFAULT_TIMESTEP_RECORDING = 20
DEFAULT_TIMESTEP_HEADLESS = 5
LUA_LOG = Path.home() / ".config/openra/Logs/lua.log"
OUT_DIR = ROOT / "out"
GAME_PROCESS = None


class Mod:
    def __init__(self, mod: str, engine_dir: str, arena: str):
        self.mod = mod
        self.engine = ROOT / engine_dir / "usr/lib/openra"
        self.bin = ROOT / engine_dir / "usr/bin"
        self.launcher = self.bin / f"openra-{mod}"
        self.utility = self.bin / f"openra-{mod}-utility"
        self.map_src = ROOT / "maps" / arena
        self.map_dst = self.engine / f"mods/{mod}/maps/opera-arena"
        self.mod_yaml = self.engine / f"mods/{mod}/mod.yaml"


MODS = {
    "ra": Mod("ra", "engine/openra", "arena"),
    "d2k": Mod("d2k", "engine/openra-d2k", "arena-d2k"),
    "cnc": Mod("cnc", "engine/openra-cnc", "arena-cnc"),
}

M = MODS["cnc"]


def sh(cmd: list[str] | str, check: bool = False, env: dict | None = None):
    return subprocess.run(cmd, capture_output=True, text=True, check=check, env=env)


def render_config(cfg: dict) -> None:
    def army(groups):
        items = ", ".join(
            '{ type = "%s", count = %d }' % (g["type"], g["count"])
            for g in groups if g["count"]
        )
        return "{ %s }" % items

    lua = (
        "-- AUTO-GENERATED by battle.py. Do not edit.\n"
        "ArmyConfig = {\n"
        f"\tAttacker = {army(cfg['attacker'])},\n"
        f"\tDefender = {army(cfg['defender'])},\n"
        f"\tGridCols = {cfg.get('grid_cols', 4)},\n"
        f"\tSeed = {cfg.get('seed', 0)},\n"
        "}\n"
    )
    (M.map_src / "config.lua").write_text(lua)


def install_map() -> str:
    if M.map_dst.exists():
        shutil.rmtree(M.map_dst)
    M.map_dst.mkdir(parents=True)
    # Copy contents rather than metadata. copytree/copy2 can carry the host's
    # SELinux label into a bind-mounted engine, making the map undeletable on
    # the next run under rootless Podman.
    for src in M.map_src.iterdir():
        if src.is_file():
            dst = M.map_dst / src.name
            shutil.copyfile(src, dst)
            os.chmod(dst, src.stat().st_mode & 0o7777)
    battle_src = ROOT / "maps/battle.lua"
    battle_dst = M.map_dst / "battle.lua"
    shutil.copyfile(battle_src, battle_dst)
    os.chmod(battle_dst, battle_src.stat().st_mode & 0o7777)
    out = sh(
        [str(M.utility), "--map-hash", str(M.map_dst)],
        check=True,
        env=dict(os.environ, DISPLAY=DISPLAY),
    )
    uid = out.stdout.strip().splitlines()[-1]
    return uid


def set_speed(timestep: int) -> None:
    timestep = int(timestep)
    if timestep < 1:
        raise ValueError("timestep must be >= 1ms/tick - 0 crashes OpenRA")
    text = M.mod_yaml.read_text()
    text = re.sub(r"\t\t%s:\n(?:\t\t\t.*\n)+" % TURBO, "", text)
    block = (
        f"\t\t{TURBO}:\n"
        f"\t\t\tName: options-game-speed.fastest\n"
        f"\t\t\tTimestep: {timestep}\n"
        f"\t\t\tOrderLatency: 6\n"
    )
    text = text.replace("\tSpeeds:\n", "\tSpeeds:\n" + block, 1)
    M.mod_yaml.write_text(text)


def start_xvfb() -> None:
    if sh(["pgrep", "-x", "Xvfb"]).returncode != 0:
        subprocess.Popen(
            ["Xvfb", DISPLAY, "-screen", "0", f"{SCREEN_W}x{SCREEN_H}x24", "-ac",
             "+extension", "GLX", "+render", "-noreset"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    for _ in range(50):
        if sh(["xdpyinfo", "-display", DISPLAY]).returncode == 0:
            return
        time.sleep(0.2)
    raise RuntimeError(f"Xvfb on {DISPLAY} did not come up")


def stop_game() -> None:
    global GAME_PROCESS
    if GAME_PROCESS is not None:
        try:
            if GAME_PROCESS.poll() is None:
                os.killpg(GAME_PROCESS.pid, signal.SIGTERM)
                GAME_PROCESS.wait(timeout=15)
        except ProcessLookupError:
            pass
        except subprocess.TimeoutExpired:
            try:
                os.killpg(GAME_PROCESS.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        finally:
            GAME_PROCESS = None
        return
    if shutil.which("systemctl") is not None:
        sh(["systemctl", "--user", "stop", GAME_UNIT])
        sh(["systemctl", "--user", "reset-failed", GAME_UNIT])


def launch_game(map_uid: str, record: bool) -> None:
    global GAME_PROCESS
    LUA_LOG.parent.mkdir(parents=True, exist_ok=True)
    LUA_LOG.write_text("")

    sh(["xdotool", "mousemove", str(SCREEN_W - 10), str(SCREEN_H - 10)],
       env=dict(os.environ, DISPLAY=DISPLAY))

    gfx = [f"Graphics.WindowedSize={SCREEN_W},{SCREEN_H}"] if record else [
        f"Graphics.WindowedSize={HEADLESS_W},{HEADLESS_H}",
        "Graphics.CapFramerate=true", "Graphics.MaxFramerate=2",
    ]
    runner = ROOT / ".run_openra.sh"
    runner.write_text(
        "#!/bin/bash\n"
        f"export DISPLAY={DISPLAY}\n"
        f'cd "{M.engine}"\n'
        f'export LD_LIBRARY_PATH="{M.engine}"\n'
        f"exec {M.launcher} Game.Mod={M.mod} Sound.Device=null"
        " Game.ViewportEdgeScroll=false"
        " Graphics.Mode=Windowed " + " ".join(gfx) +
        f" Launch.Map={map_uid}\n"
    )
    runner.chmod(0o755)

    stop_game()
    try:
        _systemd = subprocess.run(
            ["systemd-run", "--user", f"--unit={GAME_UNIT}", "--collect", str(runner)],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        _systemd = None
    if _systemd is not None and _systemd.returncode == 0:
        return

    # Molab containers do not run a user systemd manager.
    GAME_PROCESS = subprocess.Popen(
        [str(runner)],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


def start_recording(out_mp4: Path):
    return subprocess.Popen(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "x11grab",
         "-thread_queue_size", "8", "-video_size", f"{SCREEN_W}x{SCREEN_H}",
         "-framerate", "25", "-i", DISPLAY,
         "-c:v", "libvpx-vp9", "-deadline", "realtime", "-cpu-used", "8",
         "-pix_fmt", "yuv420p",
         "-b:v", "1500k", "-maxrate", "1500k", "-bufsize", "3000k",
         str(out_mp4)],
        stdin=subprocess.PIPE, stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE, start_new_session=True,
        env=dict(os.environ, DISPLAY=DISPLAY),
    )


def stop_recording(proc) -> tuple[str, bool]:
    forced = False
    try:
        proc.send_signal(signal.SIGINT)
    except ProcessLookupError:
        pass
    try:
        proc.wait(timeout=30)
    except subprocess.TimeoutExpired:
        forced = True
        # A stuck encoder should not keep the battle cell running forever.
        try:
            proc.kill()
        except ProcessLookupError:
            pass
        proc.wait()
    if proc.stderr is None:
        return "", forced
    return proc.stderr.read().decode(errors="replace"), forced


LINE_RE = re.compile(r"E\|(\w+)\s*(.*)")
FRAME_RE = re.compile(r"F\|(\d+)\|(.*)")


def parse_line(line: str):
    m = LINE_RE.search(line)
    if not m:
        return None
    kind, rest = m.group(1), m.group(2)
    kv = {}
    for tok in rest.split():
        if "=" in tok:
            k, v = tok.split("=", 1)
            kv[k] = v
    return kind, kv


def parse_frame(line: str):
    m = FRAME_RE.search(line)
    if not m:
        return None
    tick = int(m.group(1))
    units = []
    for tok in m.group(2).split(";"):
        parts = tok.split(",")
        if len(parts) == 4:
            units.append([int(p) for p in parts])
    return {"tick": tick, "units": units}


def tail_until_done(timeout: int = 360):
    events, result, frames = [], None, []
    start = time.time()
    pos = 0
    while time.time() - start < timeout:
        if LUA_LOG.exists():
            text = LUA_LOG.read_text()
            # Only consume up to the last newline: the game is still writing.
            end = text.rfind("\n", pos) + 1
            if end > pos:
                new = text[pos:end]
                pos = end
                for line in new.splitlines():
                    f = parse_frame(line)
                    if f:
                        frames.append(f)
                        continue
                    p = parse_line(line)
                    if not p:
                        continue
                    kind, kv = p
                    events.append({"kind": kind, **kv})
                    if kind == "RESULT":
                        result = kv
                    if kind == "DONE":
                        return events, result, frames
        time.sleep(POLL_S)
    raise TimeoutError(f"no E|DONE within {timeout}s")


def run_battle(spec: dict, record: bool = True, save_replay: bool = False,
               timestep: int | None = None, timeout: int = 360) -> dict:
    global M
    M = MODS[spec.get("mod", "cnc")]
    if save_replay and not record:
        raise ValueError("save_replay requires recording to be enabled")
    timestep = int(timestep or (DEFAULT_TIMESTEP_RECORDING if record
                                else DEFAULT_TIMESTEP_HEADLESS))
    started = time.time()

    render_config(spec)
    uid = install_map()
    set_speed(timestep)
    start_xvfb()
    launch_game(uid, record)

    OUT_DIR.mkdir(exist_ok=True)
    out_mp4 = OUT_DIR / "battle.webm"
    recording_tmp = (
        OUT_DIR / f".battle-{os.getpid()}-{time.time_ns()}.webm"
        if record else None
    )
    rec = start_recording(recording_tmp) if recording_tmp else None
    recording_stderr = ""
    recording_forced = False
    recording_committed = False
    try:
        try:
            events, result, frames = tail_until_done(timeout)
        finally:
            if rec is not None:
                recording_stderr, recording_forced = stop_recording(rec)
            stop_game()

        recording_stopped_cleanly = (
            rec is not None
            and rec.returncode == 255
            and not recording_forced
            and (
                "Exiting normally, received signal 2." in recording_stderr
                or not recording_stderr.strip()
            )
        )
        if rec is not None and rec.returncode != 0 and not recording_stopped_cleanly:
            detail = recording_stderr.strip()
            if recording_forced:
                detail = (
                    "ffmpeg did not exit after SIGINT and was force-killed"
                    + (f"; {detail[-1000:]}" if detail else "")
                )
            elif rec.returncode == -signal.SIGKILL:
                detail = (
                    "ffmpeg was terminated by SIGKILL, likely by the container's "
                    "OOM killer or another resource limit"
                    + (f"; {detail[-1000:]}" if detail else "")
                )
            raise RuntimeError(
                f"ffmpeg recording failed with exit code {rec.returncode}"
                + (f": {detail[-1000:]}" if detail else "")
            )
        if recording_tmp is not None:
            if not recording_tmp.exists():
                raise FileNotFoundError(
                    f"ffmpeg did not produce recording {recording_tmp}"
                )
            os.replace(recording_tmp, out_mp4)
            recording_committed = True
    finally:
        if recording_tmp is not None and not recording_committed:
            recording_tmp.unlink(missing_ok=True)

    replay_path = None
    if save_replay:
        replay_dir = OUT_DIR / "replays"
        replay_dir.mkdir(exist_ok=True)
        replay_path = replay_dir / (
            f"battle-seed-{spec.get('seed', 0)}-{time.time_ns()}.webm"
        )
        shutil.copy2(out_mp4, replay_path)

    units_meta = {int(e["id"]): e["side"] for e in events if e["kind"] == "UNIT"}
    strength = []
    for fr in frames:
        sums = {"Attacker": 0, "Defender": 0}
        for uid_, _x, _y, hp in fr["units"]:
            side = units_meta.get(uid_)
            # Frames already omit units that are dead at that point in time.
            # Filtering by the final kill set would erase their earlier HP.
            if side:
                sums[side] += hp
        strength.append({"tick": fr["tick"], **sums})

    atk_spawned = int((result or {}).get("atk_spawned", 0))
    def_spawned = int((result or {}).get("def_spawned", 0))
    stats = {
        "mod": M.mod,
        "seed": spec.get("seed", 0),
        "winner": (result or {}).get("winner", "Unknown"),
        "ticks": frames[-1]["tick"] if frames else 0,
        "ticks_per_second": 1000 // timestep,
        "spawned": {
            "Attacker": sum(1 for e in events if e["kind"] == "UNIT" and e["side"] == "Attacker")
            or atk_spawned,
            "Defender": sum(1 for e in events if e["kind"] == "UNIT" and e["side"] == "Defender")
            or def_spawned,
        },
        "survivors": {
            "Attacker": atk_spawned - int((result or {}).get("atk_lost", 0)),
            "Defender": def_spawned - int((result or {}).get("def_lost", 0)),
        },
        "kills": [
            {"tick": int(e["tick"]), "side": e["side"], "victim": e["unit"],
             "killer": e["killer"]}
            for e in events if e["kind"] == "KILL"
        ],
        "strength": strength,
        "duration_s": round(time.time() - started, 1),
        "video": str(out_mp4) if record else None,
        "replay": str(replay_path) if replay_path else None,
        "map_uid": uid,
        "result": result,
    }
    (OUT_DIR / "stats.json").write_text(json.dumps(stats, indent=2))
    return stats


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", type=Path, help="battle spec JSON")
    ap.add_argument("--attacker", help='JSON list, e.g. \'[{"type":"htnk","count":4}]\'')
    ap.add_argument("--defender", help="JSON list")
    ap.add_argument("--mod", default="cnc")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--grid-cols", type=int, default=4)
    ap.add_argument("--no-record", action="store_true")
    ap.add_argument("--save-replay", action="store_true",
                    help="save a uniquely named copy under out/replays")
    ap.add_argument("--timestep", type=int)
    ap.add_argument("--timeout", type=int, default=360)
    args = ap.parse_args()

    if args.config:
        spec = json.loads(args.config.read_text())
    else:
        attacker = json.loads(args.attacker) if args.attacker else [{"type": "htnk", "count": 4}]
        defender = json.loads(args.defender) if args.defender else [{"type": "mtnk", "count": 6}]
        spec = {"mod": args.mod, "attacker": attacker, "defender": defender,
                "seed": args.seed, "grid_cols": args.grid_cols}

    stats = run_battle(spec, record=not args.no_record,
                       save_replay=args.save_replay,
                       timestep=args.timestep, timeout=args.timeout)
    print(json.dumps({k: v for k, v in stats.items() if k != "strength"}, indent=2))


if __name__ == "__main__":
    main()
